{
 "title": "Asus RT-AX88U",
 "description": "Monitoring for Asus RT-AX88U",
 "tags": [ "asus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dbInflux", "label": "dbInflux", "query": "influxdb" },
   {
    "name": "routerHost",
    "label": "routerHost",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" "
   },
   {
    "name": "trafficHosts",
    "label": "Traffic by Host",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" "
   },
   {
    "name": "routerHostsWifi",
    "label": "Wifi Hosts",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" WHERE \"wifi\" =~ /eth./"
   },
   { "name": "intervall_basic", "label": "intervall_basic", "query": "1m,2m,5m,10m,30m,60m" },
   {
    "name": "Interfaces",
    "label": "Interfaces",
    "query": "SHOW TAG VALUES WITH KEY = \"interface\" "
   },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": "SHOW TAG VALUES WITH KEY = \"MountedOn\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "user" ], "type": "tag" },
        { "params": [ "appname" ], "type": "tag" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "procid" ], "type": "field" }
        ],
        [
         { "params": [ "facility_code" ], "type": "field" }
        ],
        [
         { "params": [ "severity_code" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=", "value": "RT-AX88U-DF18-23B7762-C" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text2",
   "gridPos": { "h": 4, "w": 11, "x": 5, "y": 2 },
   "options": {
    "content": "<span class=\"singlestat-panel-value\" style=\"font-size:60.400000000000002px\">Linux RT-AX88U on AsusWRT-Merlin </span>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.versions",
     "query": "SELECT mean(\"value\") FROM \"router.versions\" WHERE (\"host\" =~ /^$routerHost$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.versions",
     "select": [
      [
       { "params": [ "buildno" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "router.cpu",
     "query": "SELECT (100 - mean(\"idle\")) as cpu FROM \"router.cpu\" WHERE (\"host\" =~ /^$routerHost$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.filesystem",
     "select": [
      [
       { "params": [ "FreePercent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "Filesystem", "operator": "=", "value": "/dev/sda1" }
     ]
    }
   ]
  },
  {
   "title": "Free swap Space",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.swap",
     "select": [
      [
       { "params": [ "swap_free_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "RT-AX88U" }
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 6 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.mem",
     "select": [
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Swap",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.swap",
     "select": [
      [
       { "params": [ "swap_free_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 6 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Clients",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 6 },
   "targets": [
    {
     "alias": "2.4 ghz",
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_24" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    },
    {
     "alias": "5 ghz",
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "targets": [
    {
     "alias": "2.4 ghz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.temp",
     "select": [
      [
       { "params": [ "temp_24" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    },
    {
     "alias": "5 ghz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.temp",
     "select": [
      [
       { "params": [ "temp_50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "NTP Service",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open VPN Client3",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.vpnClients",
     "select": [
      [
       { "params": [ "tcp_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "vpn_client", "operator": "=", "value": "vpn_client4" }
     ]
    }
   ]
  },
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $col time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "io" ], "type": "alias" }
      ],
      [
       { "params": [ "nic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "sirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (1 min average per core)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (5 min average per core)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (15 min average per core)"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Number of Processes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "free Swap Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.swap",
     "select": [
      [
       { "params": [ "swap_free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  { "title": "Wifi / WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "📶⬆️ WiFi 5ghz upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth7" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth7" }
     ]
    }
   ]
  },
  {
   "title": "📶⬇️ WiFi 5ghz down",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth7" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "🛰️⬆️ WAN out",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "🛰️⬇️  WAN in",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "📶⬆️ WiFi 2.4ghz upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth6" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth6" }
     ]
    }
   ]
  },
  {
   "title": "📶⬇️ WiFi 2.4ghz down",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth6" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth6" }
     ]
    }
   ]
  },
  {
   "title": "🛰️ Traffic Router to WAN ETH0",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth0" }
     ]
    }
   ]
  },
  {
   "title": "Connected WiFi Clients",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2,4ghz Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "wifi_5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5ghz Clients" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Filesystem $filesystem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "repeat": "filesystem",
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.filesystem",
     "select": [
      [
       { "params": [ "Available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "Used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Used" ], "type": "alias" }
      ],
      [
       { "params": [ "blocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "MountedOn", "operator": "=~", "value": "/^$filesystem$/" }
     ]
    }
   ]
  },
  { "title": "VPN / TUN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "OpenVPN Client3 ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.vpnClients",
     "select": [
      [
       { "params": [ "auth_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Auth read" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TCP/UDP read " ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TCP/UDP write" ], "type": "alias" }
      ],
      [
       { "params": [ "tun_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TUN/TAP read " ], "type": "alias" }
      ],
      [
       { "params": [ "tun_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TUN/TAP write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "🛰️ VPN Traffic TUN14",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "tun14" }
     ]
    }
   ]
  },
  { "title": "Wifi rsi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Wifi rssi",
   "type": "gauge",
   "description": "-30 dBm \tAmazing \t\n-67 dBm \tVery Good \t\n-70 dBm \tOkay \t\n-80 dBm \tNot Good \t\n-90 dBm \tUnusable \t",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Clients rssi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname ($tag_client) [$tag_ip]",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise Antenna",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "noise_antenna_1" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  { "title": "Connstats / Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Ping & Jitter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.uptime",
     "select": [
      [
       { "params": [ "Ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Jitter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.uptime",
     "select": [
      [
       { "params": [ "Jitter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Packet_Loss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.uptime",
     "select": [
      [
       { "params": [ "Packet_Loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.spdstats",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest Upload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.spdstats",
     "select": [
      [
       { "params": [ "Upload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Traffic by Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Traffic by Client - out",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "outBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic by Client - in",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "inBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Client actual Traffic Download",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "alias": "$col $tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.trafficAnalyzer",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  { "title": "$trafficHosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 }, "repeat": "trafficHosts" },
  {
   "title": "App Download",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 118 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "query": "SELECT \"rx\", \"tx\" FROM \"router.traffic\" WHERE (\"mac\" = '18:31:BF:53:F1:C2') AND $timeFilter GROUP BY \"mac\", \"cat_name\" ",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Download" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "title": "App Upload",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 118 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_app_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "app_name" ], "type": "tag" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "query": "SELECT \"rx\", \"tx\" FROM \"router.traffic\" WHERE (\"mac\" = '18:31:BF:53:F1:C2') AND $timeFilter GROUP BY \"mac\", \"cat_name\" ",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "select": [
      [
       { "params": [ "mac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Category Download",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 118 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_cat_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "cat_name" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "query": "SELECT \"rx\", \"tx\" FROM \"router.traffic\" WHERE (\"mac\" = '18:31:BF:53:F1:C2') AND $timeFilter GROUP BY \"mac\", \"cat_name\" ",
     "select": [
      [
       { "params": [ "rx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Category Upload",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 118 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$tag_cat_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" },
      { "params": [ "cat_name" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.trafficAnalyzer",
     "query": "SELECT \"rx\", \"tx\" FROM \"router.traffic\" WHERE (\"mac\" = '18:31:BF:53:F1:C2') AND $timeFilter GROUP BY \"mac\", \"cat_name\" ",
     "select": [
      [
       { "params": [ "tx" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 120 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "in",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "inBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    },
    {
     "alias": "out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "mac" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "outBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  },
  { "title": "$routerHostsWifi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 }, "repeat": "routerHostsWifi" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 129 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "wifiBand" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "wifiBand" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 129 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "online" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 129 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "online" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 129 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "online" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 129 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 129 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "select": [
      [
       { "params": [ "online" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT moving_average(\"rsi_antenna1\", 5), moving_average(\"rsi_antenna2\", 5), moving_average(\"rsi_antenna3\", 5), moving_average(\"rsi_antenna4\", 5), moving_average(\"rssi\", 20) FROM \"router.wifi.clients\" WHERE (\"hostname\" =~ /^$routerHostsWifi$/) AND $timeFilter GROUP BY \"hostname\", \"client\", \"ip\"",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" },
       { "params": [ "rsi" ], "type": "alias" }
      ],
      [
       { "params": [ "rsi_antenna1" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "antenna1" ], "type": "alias" }
      ],
      [
       { "params": [ "rsi_antenna2" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "antenna2" ], "type": "alias" }
      ],
      [
       { "params": [ "rsi_antenna3" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "antenna3" ], "type": "alias" }
      ],
      [
       { "params": [ "rsi_antenna4" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "antenna4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 131 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "noise_antenna_1" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Noise Antenna 1" ], "type": "alias" }
      ],
      [
       { "params": [ "noise_antenna_2" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Noise Antenna 2" ], "type": "alias" }
      ],
      [
       { "params": [ "noise_antenna_3" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Noise Antenna 3" ], "type": "alias" }
      ],
      [
       { "params": [ "noise_antenna_4" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "Noise Antenna 4" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "title": "Rx/Tx ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 131 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "rx_rate_pkt" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "rx_rate_pkt" ], "type": "alias" }
      ],
      [
       { "params": [ "tx1_rate_pkt" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "tx1_rate_pkt" ], "type": "alias" }
      ],
      [
       { "params": [ "tx2_rate_pkt" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "tx2_rate_pkt" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "title": "2.4 / 5Ghz Channel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 131 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "alias": "WifiBand",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "wifiBand" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Network traffic on $Interfaces ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
   "repeat": "Interfaces",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interfaces$/" }
     ]
    }
   ]
  },
  { "title": "Workstations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "$trafficHosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 150 },
   "repeat": "trafficHosts",
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "inBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "outBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  }
 ]
}